### ISSUE TITLE
Have our own DB type

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/QuerySQLite.jl#2]
I think it would be nice if one could write
```julia
database = QuerySQLite.DB(filename)
```
instead of
```julia
database = NamedTuple(OutsideTables(DB(filename)))
```
Where we have our own `QuerySQLite.DB` type that overwrites `getproperty`.

It could also have a nice `show` method that displays all the tables in that db.

**Comment by bramtayl** [comment]
https://github.com/queryverse/QuerySQLite.jl/commit/c41958a3b33dfe5e6a29bb56b0b9c3b0875d3703 simplifies this to

```julia
database = outside_tables(DB(filename))
```

which is a little nicer, anyway
