### ISSUE TITLE
Problem when using @map

### ISSUE THREAD

**Issue by pstaabp** [queryverse/QuerySQLite.jl#28]
Another problem that I found was using the `@map` command. In this example:

```
database.Track |> 
    @groupby(_.AlbumId) |> 
    @map({AlbumId = key(_), time_min = minimum(_.Milliseconds)})
```

returns the error:
```
MethodError: no method matching iterate(::QuerySQLite.SourceCode{SQLite.DB})
```

This seems to be because Julia's `minimum` function uses `iterate` under the hood.  It seems that it would be nice for this to translate into something like:
```
SELECT AlbumID, MIN(Milliseconds) FROM Track GROUP BY AlbumID;
```

and run the `MIN` function from SQLITE instead.

**Comment by bramtayl** [comment]
Yes, thanks for testing out the package. Can you open up a separate issue for `minimum`?

**Comment by bramtayl** [comment]
Oh, nevermind, for some reason I thought this was the same issue. Carry on!
